### ISSUE TITLE
EVA struts causing unplanned spontaneous dissassembly

### ISSUE THREAD

**Issue by Patupi** [KospY/KAS#74] opened 2013-11-21 10:12 UTC
This seems random, and could be an issue with two conflicting torque systems, but when two vessels dock together and a Kerbal EVAs to use the KAS connectable struts to strengthen the connection, sometimes on the second or third connection the craft violently rips apart. Sometimes it merely rips the connector off which jumps into 'ridiculous speed', but more likely the whole area at docking port is sheered off.

It seems random in effect and I've successfully reloaded and recreated the problem, but also managed (after multiple attempts) to finally connect four struts by saving and loading before connecting each one. At other times the strut connection on the same craft has had no issues at all. Docking orientation and the resultant angle of the struts seems not to affect whether this happens or not.

**Comment by ihsoft** [comment] 2016-06-12 23:50
It looks like a physics behavior which has changed dramatically in KSP 1.1. I close this issue for now. Feel free to reopen it if you get the same behavior in 1.1 as well.

**Closed by ihsoft** 2016-06-12 23:50 UTC
Labels: bug

**Comment by d4goxn** [comment] 2017-02-18 00:10
This is still happening, and I have a quicksave that can reliably reproduce it. I'll make a copy in case anyone wants to look at it. With this quicksave, there are two ways of blowing everything up:

- Burn, timewarp, return to normal: Core module of drill rig shakes apart and parts go flying.
- Weld the docking ports: Vessels turn off physics, ports dissapear,  vessels instantly close the distance between them and connect, and then turn physics back on. Core module explodes and parts go flying. They fly unidirectionally away from the overall CoM, they are not flung to aft by the weld warp.

### Vessel details

- Two vessels ("Master Blaster" skycrane and drill rig) joined after separate orbital constructions, with Ubio Construction docking ports.
- Mass: 185,000 Kg. This is probably about as dense as a legit vehicle gets in KSP, until you start drop-shipping big crates of bulk construction supplies.
- 4 EVA struts supporting weak docking port joint, connected to main structural / load bearing module of each vessel.

Here is the overall vessel, with the Kerbal Engineering info.

![glitchcraft](https://cloud.githubusercontent.com/assets/3030411/23087307/0a87d4c0-f528-11e6-8b22-978458992b0c.png)

Here is a closeup of the four EVA struts that bridge across the docking connection, showing what they are connected to.

![kas-strut-detail](https://cloud.githubusercontent.com/assets/3030411/23087323/20994f1e-f528-11e6-8be5-c03d4488d921.png)

### Observations

- Explosions are often preceded by crazy vibrations that rapidly increase in amplitude. What drives this? Where does the physics engine get the kinetic energy from? Where is the potential energy stored? Not in an elastic collision, these two vessels were built separately, and are unable to clip through each other during docking.
- I have seen this type of failure (extreme vibration increasing to destruction) once before, when I tested a very heavy vessel on a weak landing module. For some reason, instead of just crushing the landing module, a more centralized, but still largely load bearing, module vibrated the craft apart.
- Suspending 200 tons by four struts, in a ~1G acceleration + engine vibration, might be unreasonable. In that case it would make sense for the four struts together to destroy the part that they are holding. However, this shouldn't happen while free floating after time warp. When there is no energy being put into the craft (e.g. burning engine thrust), existing vibrations should not amplify (not the fault of this mod, I am sure).

### More Data

I can't post a zipped save file here, but I've kept a copy in case anyone asks for it.

**Comment by d4goxn** [comment] 2017-02-18 00:23
Whoa, just noticed the 0.7.3 beta release. `beta4` sounds pretty skookum, let me try that out...
