### ISSUE TITLE
Screwdriver roullette(possibly whole inventory)

### ISSUE THREAD

**Issue by inucune** [KospY/KAS#151] opened 2015-07-17 09:18 UTC
The electric screwdriver does not always stay with a kerbal when transferring a kerbal from one part of a ship to another using the crew hatch menu. the kerbal's inventory can end up on another kerbal through the same method. If a kerbal is moved via eva, this issue is not present.

**Comment by inucune** [comment] 2015-07-21 05:44
Update: Any kerbal entering the Academy will have their inventory swallowed by it.

**Comment by Kerbas-ad-astra** [comment] 2015-07-21 16:49
The issue is that the Academy has no IVA, which (I think) is important to how KIS tracks inventories from Kerbals to seats.  The next version of MKS should resolve this, or you can grab a mod/patch called "Crew Portraits" if you want a fix right now.

**Comment by KospY** [comment] 2015-07-31 22:23
This problem is related to KIS not KAS, so I'm closing this.
Anyway for information this issue will be fixed in the next version of KIS.

**Closed by KospY** 2015-07-31 22:23 UTC
Labels: invalid
